### ISSUE TITLE
Refactor jobs pipeline to drop beam

### ISSUE THREAD

**Issue by sethvargo** [abcxyz/github-metrics-aggregator#275]
### TL;DR

Just like we did for the leech pipeline, we should drop beam and move to Cloud Run jobs.

**Comment by bradegler** [comment]
Implementation change in #279

**Comment by lock14** [comment]
terraform modules are finished and autopush and integration environments are updated. Here is current status:

Steps to complete:

* [x] Convert code to Cloud Run job format #279 
* [x] Update terraform modules
* [x] Fix deployments for autopush & integ
* [ ] Fix production
* [ ] Remove / Decomission dataflow jobs in all environements (autopush, integration, and production)

**Comment by lock14** [comment]
This is finished now.
